const SkillsData = [
    { name: "C", imagePath: "/skills-images/c.png" },
    { name: "C#", imagePath: "/skills-images/c-sharp.png" },
    { name: "C++", imagePath: "/skills-images/cpp.png" },
    { name: "HTML", imagePath: "/skills-images/html-5.png" },
    { name: "CSS", imagePath: "/skills-images/css.png" },
    { name: "JavaScript", imagePath: "/skills-images/js.png" },
    { name: "Java", imagePath: "/skills-images/java.png" },
    { name: "SQL", imagePath: "/skills-images/sql.png" },
    { name: "Python", imagePath: "/skills-images/python.png" },
    { name: "R", imagePath: "/skills-images/r.png" },
    { name: "Visual Studio", imagePath: "/skills-images/vs.png" },
    { name: "Visual Studio Code", imagePath: "/skills-images/vs-code.png" },
    { name: "Git", imagePath: "/skills-images/git.png" },
    { name: "GitHub", imagePath: "/skills-images/github.png" },
    { name: "Oracle Apex", imagePath: "/skills-images/oracle.png" },
    { name: "Node.js", imagePath: "/skills-images/node-js.png" },
    { name: "Windows", imagePath: "/skills-images/windows.png" },
    { name: "Android", imagePath: "/skills-images/android.png" },
    { name: "Mac OS", imagePath: "/skills-images/mac-os.png" },
    { name: "iOS", imagePath: "/skills-images/ios.png" },
    { name: "Linux", imagePath: "/skills-images/linux.png" },
    { name: ".NET Framework", imagePath: "/skills-images/dot-net.png" },
    { name: "Web Assembly", imagePath: "/skills-images/wasm.png" },
    { name: "Avalonia", imagePath: "/skills-images/avalonia.png" },
    { name: "React", imagePath: "/skills-images/react.png" },
    { name: "Next.js", imagePath: "/skills-images/nextjs.png" },
    { name: "Arduino", imagePath: "/skills-images/arduino.png" },
];

export default SkillsData;
